version: "3.1"
services:

  redis:
    container_name: dev-redis
    image: redis:5.0-rc-alpine
    volumes:
      - ./redis:/data
    ports:
      - "16379:6379"

  mongo:
    container_name: dev-mongo
    image: mongo:4
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"

  mysql:
    container_name: dev-mysql
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  pgsql:
    container_name: dev-pgsql
    image: postgres
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: root
